import { Project, Task, AIPrompt, ScreenshotKB, LearningJournal } from '@/types';

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Trading AI',
    description: 'Algorithmic trading bot with Machine Learning, backtesting EMA and RSI indicators.',
    color: '#10b981',
    status: 'active',
    progress: 65,
    deadline: '2026-11-15T00:00:00Z',
    tags: ['Python', 'Machine Learning', 'Finance', 'Crypto'],
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    name: 'Thesis',
    description: 'Academic thesis on Distributed Computing and high-throughput real-time architectures.',
    color: '#6366f1',
    status: 'active',
    progress: 40,
    deadline: '2026-12-20T00:00:00Z',
    tags: ['Academic', 'Research', 'Distributed Systems'],
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-3',
    name: 'Data Science Learning',
    description: 'Mastering Pandas, Polars, Scikit-Learn, PyTorch and deep statistical modeling.',
    color: '#f59e0b',
    status: 'active',
    progress: 80,
    deadline: '2026-10-30T00:00:00Z',
    tags: ['Python', 'Data Science', 'Statistics'],
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-4',
    name: 'DNI Analytics',
    description: 'Corporate real-time analytics dashboard and metrics ingestion pipeline.',
    color: '#06b6d4',
    status: 'planning',
    progress: 20,
    deadline: '2026-12-01T00:00:00Z',
    tags: ['Dashboard', 'SQL', 'Next.js'],
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj-5',
    name: 'English Learning',
    description: 'IELTS preparation, daily vocabulary retention and active conversation practice.',
    color: '#ec4899',
    status: 'active',
    progress: 50,
    deadline: '2026-11-30T00:00:00Z',
    tags: ['Language', 'IELTS', 'Vocabulary'],
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    project_id: 'proj-1',
    title: 'Implementasi Backtest EMA 20 & EMA 50 Crossover',
    description: 'Validasi win-rate dan Sharpe ratio pada time-frame 15m BTC/USDT selama 1 tahun data historis.',
    status: 'done',
    priority: 'high',
    start_date: new Date(Date.now() - 7 * 86400000).toISOString(),
    due_date: new Date().toISOString(),
    reminder: new Date().toISOString(),
    color_label: '#10b981',
    completed: true,
    checklist: [
      { id: 'c1', text: 'Fetch 1-year Binance OHLCV data', completed: true },
      { id: 'c2', text: 'Hitung EMA 20 dan EMA 50 dengan Pandas', completed: true },
      { id: 'c3', text: 'Plot visualisasi backtest drawdown', completed: true },
    ],
    ai_prompt: 'Buatkan script Python vectorized backtest strategi EMA crossover dengan fee 0.05% per trade.',
    notes: 'Hasil Sharpe Ratio = 1.84, Max Drawdown = 12.3%. Perlu filtering volume saat market sideway.',
    attachments: [
      { name: 'backtest_result.csv', url: '#', type: 'application/csv', size: 12400 }
    ],
    screenshots: [
      { name: 'EMA Chart', url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=60' }
    ],
    order_index: 0,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'task-2',
    project_id: 'proj-1',
    title: 'Setup Realtime WebSocket Webhook Binance API',
    description: 'Integrasikan stream order book dan live price tick menggunakan async WebSocket.',
    status: 'in_progress',
    priority: 'high',
    start_date: new Date().toISOString(),
    due_date: new Date(Date.now() + 2 * 86400000).toISOString(),
    reminder: new Date(Date.now() + 1 * 86400000).toISOString(),
    color_label: '#10b981',
    completed: false,
    checklist: [
      { id: 'c4', text: 'Handle WebSocket auto-reconnect', completed: true },
      { id: 'c5', text: 'Simpan tick buffer ke Redis', completed: false },
    ],
    ai_prompt: 'Bagaimana cara robust handle websocket disconnection di Python asyncio websockets?',
    notes: 'Gunakan Exponential Backoff untuk retry reconnect bila server drop.',
    attachments: [],
    screenshots: [],
    order_index: 1,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'task-3',
    project_id: 'proj-2',
    title: 'Review Chapter 3: Metodologi Penelitian & Desain Sistem',
    description: 'Selesaikan diagram arsitektur microservices dan formal mathematical notation.',
    status: 'review',
    priority: 'medium',
    start_date: new Date(Date.now() - 3 * 86400000).toISOString(),
    due_date: new Date(Date.now() + 3 * 86400000).toISOString(),
    reminder: null,
    color_label: '#6366f1',
    completed: false,
    checklist: [
      { id: 'c6', text: 'Koreksi sitasi IEEE format', completed: true },
      { id: 'c7', text: 'Proofread tata bahasa dengan Claude', completed: true },
      { id: 'c8', text: 'Review dosen pembimbing', completed: false },
    ],
    ai_prompt: null,
    notes: 'Dosen meminta penambahan perbandingan latency gRPC vs REST API.',
    attachments: [],
    screenshots: [],
    order_index: 2,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'task-4',
    project_id: 'proj-3',
    title: 'Eksperimen Optimasi Hyperparameter Random Forest',
    description: 'Gunakan Optuna untuk hyperparameter search pada klasifikasi churn pelanggan.',
    status: 'todo',
    priority: 'medium',
    start_date: null,
    due_date: new Date(Date.now() + 5 * 86400000).toISOString(),
    reminder: null,
    color_label: '#f59e0b',
    completed: false,
    checklist: [
      { id: 'c9', text: 'Setup objective function di Optuna', completed: false },
      { id: 'c10', text: 'Evaluasi F1-Score & ROC-AUC', completed: false },
    ],
    ai_prompt: 'Contoh implementasi Optuna search untuk n_estimators, max_depth, dan min_samples_split.',
    notes: '',
    attachments: [],
    screenshots: [],
    order_index: 3,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'task-5',
    project_id: 'proj-5',
    title: 'Pelajari 20 Academic Collocations IELTS Writing Task 2',
    description: 'Catat contoh kalimat yang sering keluar pada topik Technology & Environment.',
    status: 'backlog',
    priority: 'low',
    start_date: null,
    due_date: new Date(Date.now() + 7 * 86400000).toISOString(),
    reminder: null,
    color_label: '#ec4899',
    completed: false,
    checklist: [],
    ai_prompt: 'Berikan 20 collocations level C1 untuk IELTS essay tema artificial intelligence.',
    notes: 'Focus on phrases like "unprecedented technological leap", "foster innovation".',
    attachments: [],
    screenshots: [],
    order_index: 4,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_PROMPTS: AIPrompt[] = [
  {
    id: 'prompt-1',
    project_id: 'proj-1',
    title: 'Optimasi Python Vectorized Indicator EMA & ATR',
    prompt: 'Tuliskan fungsi Python performa tinggi menggunakan NumPy / Numba untuk menghitung Exponential Moving Average dan ATR tanpa looping iteratif yang lambat pada data 1 juta baris.',
    ai_output: '```python\nimport numpy as np\nfrom numba import jit\n\n@jit(nopython=True)\ndef calc_ema(prices, period):\n    alpha = 2.0 / (period + 1.0)\n    ema = np.empty_like(prices)\n    ema[0] = prices[0]\n    for i in range(1, len(prices)):\n        ema[i] = alpha * prices[i] + (1.0 - alpha) * ema[i - 1]\n    return ema\n```\nNumba JIT mempercepat eksekusi hingga 80x dibanding iterasi python biasa.',
    model: 'Claude',
    tags: ['trading', 'python', 'numba', 'optimasi'],
    rating: 5,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prompt-2',
    project_id: 'proj-3',
    title: 'Exploratory Data Analysis Boilerplate dengan Polars',
    prompt: 'Berikan script cepat untuk profiling missing values, skewness, dan correlation matrix menggunakan Polars daripada Pandas.',
    ai_output: '```python\nimport polars as pl\n\ndf = pl.read_parquet("dataset.parquet")\nprint(df.null_count())\nprint(df.select(pl.all().skew()))\ncorr = df.select([pl.col(col) for col in df.columns if df[col].dtype.is_numeric()]).corr()\nprint(corr)\n```',
    model: 'ChatGPT',
    tags: ['data science', 'polars', 'eda'],
    rating: 4,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prompt-3',
    project_id: 'proj-5',
    title: 'IELTS Writing Task 2 Complex Grammar Rephrase',
    prompt: 'Rephrase this sentence using inversion and passive voice: "If governments do not invest in green energy, future generations will suffer severe environmental consequences."',
    ai_output: '"Should governments fail to invest in green energy, severe environmental consequences will inevitably be borne by future generations."\n\n*Explanation*: Uses conditional inversion ("Should governments fail...") and passive construction ("will be borne by...").',
    model: 'Gemini',
    tags: ['bahasa inggris', 'ielts', 'grammar'],
    rating: 5,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prompt-4',
    project_id: 'proj-2',
    title: 'Docker Multi-stage Build untuk Go Microservice',
    prompt: 'Buatkan Dockerfile multi-stage build yang sangat minimalis untuk service Go dengan distroless scratch image dan non-root security context.',
    ai_output: '```dockerfile\nFROM golang:1.24-alpine AS builder\nWORKDIR /app\nCOPY go.mod go.sum ./\nRUN go mod download\nCOPY . .\nRUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o server .\n\nFROM gcr.io/distroless/static-debian12\nWORKDIR /\nCOPY --from=builder /app/server /server\nUSER nonroot:nonroot\nENTRYPOINT ["/server"]\n```',
    model: 'DeepSeek',
    tags: ['docker', 'devops', 'microservices'],
    rating: 5,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_SCREENSHOTS: ScreenshotKB[] = [
  {
    id: 'ss-1',
    project_id: 'proj-1',
    title: 'Chart Analisis EMA 20 & 50 Bullish Crossover',
    image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1000&auto=format&fit=crop&q=80',
    description: 'Screenshot sinyal buy terkonfirmasi saat EMA 20 memotong ke atas EMA 50 didukung lonjakan volume 2.5x rata-rata.',
    tags: ['trading', 'chart', 'ema', 'technical-analysis'],
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ss-2',
    project_id: 'proj-2',
    title: 'Diagram Arsitektur Microservices Thesis',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1000&auto=format&fit=crop&q=80',
    description: 'Arsitektur komunikasi event-driven Kafka broker dengan service worker nodes.',
    tags: ['architecture', 'microservices', 'diagram', 'thesis'],
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ss-3',
    project_id: 'proj-3',
    title: 'Heatmap Korelasi Feature Matrix Dataset',
    image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1000&auto=format&fit=crop&q=80',
    description: 'Hasil korelasi Pearson. Fitur X3 dan X7 mengalami multikolinearitas tinggi (0.89) sehingga X7 di-drop.',
    tags: ['data science', 'heatmap', 'statistics'],
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_LEARNING_NOTES: LearningJournal[] = [
  {
    id: 'note-1',
    project_id: 'proj-1',
    title: 'Pelajaran Penting dari Backtest Slippage & Fee',
    what_learned: 'Strategi scalping dengan win-rate 70% di backtest teoritis ternyata merugi ketika diaplikasikan dengan spread nyata dan taker fee 0.05%.',
    insights: 'High frequency trading sangat sensitif terhadap execution latency dan exchange fee structure. Semakin pendek time frame, semakin besar proporsi fee memakan profit.',
    mistakes: 'Mengasumsikan order terisi tepat di close price tanpa memperhitungkan slippage pada volume tinggi.',
    solutions: 'Beralih ke time frame 15m - 1h dengan profit target minimal 3x dari estimasi total trading fee + slippage buffer.',
    next_steps: 'Implementasikan limit-order execution strategy daripada market order.',
    tags: ['trading', 'risk management', 'slippage'],
    date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'note-2',
    project_id: 'proj-3',
    title: 'Optimasi Polars vs Pandas pada Dataset 10GB',
    what_learned: 'Polars menggunakan Rust dan Apache Arrow memory layout sehingga lazy execution mampu query dataset 10GB tanpa Out Of Memory (OOM).',
    insights: 'LazyFrames (`scan_parquet`) menunda eksekusi sampai query optimizer selesai menyusun rencana eksekusi dan memotong kolom yang tidak dipakai lebih awal.',
    mistakes: 'Langsung memuat seluruh dataset ke memory dengan eager evaluation `read_parquet()` saat hanya membutuhkan 3 kolom.',
    solutions: 'Gunakan `pl.scan_parquet().filter(...).select(...).collect()` untuk mengeksploitasi predicate pushdown.',
    next_steps: 'Uji performa multi-threading streaming mode di server 16 cores.',
    tags: ['python', 'polars', 'performance'],
    date: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0],
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
